//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author CHENGE
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Lc.Bht.Model
{
    ///<summary>
    ///主板安装内存
    ///</summary>
    [SugarTable("pp_memory")]
    public class PpMemory
    {
          public PpMemory()
          {
          }

           /// <summary>
           /// 描述 : 主键 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "主键")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string id {get;set;}

           /// <summary>
           /// 描述 : 主板id 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "主板id")]           
           public string pcb_id {get;set;}

           /// <summary>
           /// 描述 : 内存sn 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "内存sn")]           
           public string memo_sn {get;set;}

           /// <summary>
           /// 描述 : 内存安装点位 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "内存安装点位")]           
           public string memo_loc {get;set;}

           /// <summary>
           /// 描述 : 内存料号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "内存料号")]           
           public string memo_code {get;set;}

           /// <summary>
           /// 描述 : 内存压力（预估值） 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "内存压力（预估值）")]           
           public int? memo_plan_pressure {get;set;}

           /// <summary>
           /// 描述 : 内存压力（实际值） 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "内存压力（实际值）")]           
           public int? memo_actual_pressure {get;set;}

           /// <summary>
           /// 描述 : 内存真假属性 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "内存真假属性")]           
           public bool? memo_tf {get;set;}

           /// <summary>
           /// 描述 : 相对路劲 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "相对路劲")]           
           public string img_path {get;set;}

           /// <summary>
           /// 描述 : 节拍 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "节拍")]           
           public string rhythm {get;set;}

           /// <summary>
           /// 描述 : 创建时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "创建时间")]           
           public DateTime? creation_time {get;set;}

           /// <summary>
           /// 描述 : 更新时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "更新时间")]           
           public DateTime? updata_time {get;set;}

    }
}